### ISSUE TITLE
关于4K显示器最高只能用2K或以下分辨率的问题，config配置有问题

### ISSUE THREAD

**Issue by Charley-Tang** [DrSkilled/Hackintosh_MSI_B460M_MORTAR-i5_10500_iGPU_UHD630_6600XT#5]
参考帖子：https://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1849099
核显配置里`framebuffer-stolenmem`给了`00003001`，删掉就可以4K分辨率了

framebuffer-stolenmem（给 BIOS 中 DVMT 添加一点内存大小，会影响高分屏，这个值必须大于 32M，也不应该过高）：
* 一般 1080P 屏幕的话，设置为 48M 就够用了：00003001
* 当你的笔记本电脑屏幕是 2k，你可以设置为 64M：00000004
* 4K 屏的话，要设置为 128M：00000008
如果你的 BIOS 中可以设置 DVMT 的话并且你设置成为 128M 之后，可以不需要设置这个属性，或者这个属性设置小一点：00003001 保险起见，高分屏直接设置成 128M 比较稳，并且保证在 BIOS 能设置 DVMT 的情况下设置在 64M 或以下 （PS：这一部分可能有误，但是最后一句保险起见，高分屏直接设置成 128M 比较稳是试验过的）

**Comment by KalonPeng** [comment]
感谢，由于我本人用的是2k屏幕，没有遇到这个问题，下一版我参考修改一下～

**Comment by Charley-Tang** [comment]
@DrSkilled 
这个主板BIOS可以设置DVMT，不需要framebuffer-stolenmem这个参数

**Comment by KalonPeng** [comment]
> @DrSkilled 这个主板BIOS可以设置DVMT，不需要framebuffer-stolenmem这个参数

感谢，已修复，拖了这么久，这次终于更新了～
